area_area = 'https://api-dbw.stat.gov.pl/api/1.1.0/area/area-area'
area_variable = 'https://api-dbw.stat.gov.pl/api/1.1.0/area/area-variable'
date_dictionary = 'https://api-dbw.stat.gov.pl/api/1.1.0/dictionaries/date-dictionary'
periods_dictionary = 'https://api-dbw.stat.gov.pl/api/1.1.0/dictionaries/periods-dictionary'
way_of_presentation = 'https://api-dbw.stat.gov.pl/api/1.1.0/dictionaries/way-of-presentation'
variable_data_section = 'https://api-dbw.stat.gov.pl/api/1.1.0/variable/variable-data-section'
variable_section_periods = 'https://api-dbw.stat.gov.pl/api/1.1.0/variable/variable-section-periods'
variable_section_position = 'https://api-dbw.stat.gov.pl/api/1.1.0/variable/variable-section-position'
variable_meta = 'https://api-dbw.stat.gov.pl/api/1.1.0/variable/variable-meta'

